version: '3.7'
services:

    php8-changes-php-fpm:
        image: ${REGISTRY}/php8-changes-php-fpm:${IMAGE_TAG}
        volumes:
            - .:/var/www/html

    php8-changes-php-cli:
        image: ${REGISTRY}/php8-changes-php-cli:${IMAGE_TAG}
        volumes:
            - .:/app

    php8-changes-nginx:
        image: ${REGISTRY}/php8-changes-nginx:${IMAGE_TAG}
        ports:
            - ${APP_WEB_PORT}:80
        volumes:
            - .:/var/www/html